workflows:
    default-workflow:
        environment:
            flutter: stable
        triggering:
          events:
            - tag
            - push
        scripts:
          - name: Set up local.properties
            script: | 
              echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          - name: Get Flutter packages
            script: | 
              flutter packages pub get
          - name: Build APK with Flutter
            script: | 
              flutter build apk --flavor development --target lib/main_development.dart --debug
        artifacts:
          - build/**/outputs/**/*.aab
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
        publishing: 
          email:
            recipients:
              - gedeivanpratama@gmail.com
            notify:
              success: true
              failure: false