name: guternberg_book
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.5
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  stream_transform: ^2.1.0
  webview_flutter: ^4.8.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  flutter_lints: ^3.0.0
  test: ^1.24.9
  hive_generator: ^2.0.1



flutter:
  uses-material-design: true
  generate: true
