name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4.2.2
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4.2.2
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --flavor production --target lib/main_production.dart --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4.2.2
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle --flavor development --target lib/main_development.dart --release